---
- name: Pre-pull master system container image
  command: >
    atomic pull --storage=ostree {{ openshift.common.system_images_registry }}/{{ openshift.master.master_system_image }}:{{ openshift_image_tag }}
  register: pull_result
  changed_when: "'Pulling layer' in pull_result.stdout"
  when: openshift.common.is_containerized | bool and openshift.common.is_master_system_container | bool

- name: Check Master system container package
  command: >
    atomic containers list --no-trunc -a -f container={{ openshift.common.service_type }}-master
  register: result
  when: openshift.common.is_containerized | bool and openshift.common.is_master_system_container | bool

- name: Update Master system container package
  command: >
    atomic containers update {{ openshift.common.service_type }}-master
  register: update_result
  changed_when: "'Extracting' in update_result.stdout"
  when:
    - openshift.common.is_containerized | bool
    - openshift.common.is_master_system_container | bool
    - openshift.common.version == openshift_version and "master" in result.stdout

- name: Uninstall Master system container package
  command: >
    atomic uninstall {{ openshift.common.service_type }}-master
  failed_when: False
  when:
    - openshift.common.is_containerized | bool
    - openshift.common.is_master_system_container | bool
    - openshift.common.version != openshift_version and "master" in result.stdout

- name: Install Master system container package
  command: >
    atomic install --system --name={{ openshift.common.service_type }}-master {{ openshift.common.system_images_registry }}/{{ openshift.master.master_system_image }}:{{ openshift_image_tag }}
  when:
    - openshift.common.is_containerized | bool
    - openshift.common.is_master_system_container | bool
    - openshift.common.version != openshift_version or "master" not in result.stdout
  notify:
    - restart master
