---
- name: Pre-pull node system container image
  command: >
    atomic pull --storage=ostree {{ openshift.common.system_images_registry }}/{{ openshift.node.node_system_image }}:{{ openshift_image_tag }}
  register: pull_result
  changed_when: "'Pulling layer' in pull_result.stdout"
  when:
  - openshift.common.is_containerized | bool
  - openshift.common.is_node_system_container | bool

- name: Pre-pull OpenVSwitch system container image
  command: >
    atomic pull --storage=ostree {{ openshift.common.system_images_registry }}/{{ openshift.node.ovs_system_image }}:{{ openshift_image_tag }}
  register: pull_result
  changed_when: "'Pulling layer' in pull_result.stdout"
  when:
  - openshift.common.is_containerized | bool
  - openshift.common.use_openshift_sdn | bool
  - openshift.common.is_openvswitch_system_container | bool

- name: Check Node system container package
  command: >
    atomic containers list --no-trunc -a -f container={{ openshift.common.service_type }}-node
  register: result
  when:
  - openshift.common.is_containerized | bool
  - openshift.common.is_node_system_container | bool

- name: Update Node system container package
  command: >
    atomic containers update {{ openshift.common.service_type }}-node
  register: update_result
  changed_when: "'Extracting' in update_result.stdout"
  when:
  - openshift.common.is_containerized | bool
  - openshift.common.is_master_system_container | bool
  - openshift.common.version == openshift_version and "node" in result.stdout

- name: Uninstall Node system container package
  command: >
    atomic uninstall {{ openshift.common.service_type }}-node
  failed_when: False
  when:
  - openshift.common.is_containerized | bool
  - openshift.common.is_node_system_container | bool
  - openshift.common.version != openshift_version and "node" in result.stdout

- name: Install Node system container package
  command: >
    atomic install --system --name={{ openshift.common.service_type }}-node {{ openshift.common.system_images_registry }}/{{ openshift.node.node_system_image }}:{{ openshift_image_tag }}
  register: install_node_result
  changed_when: "'Extracting' in pull_result.stdout"
  when:
  - openshift.common.is_containerized | bool
  - openshift.common.is_node_system_container | bool
  - openshift.common.version != openshift_version or "node" not in result.stdout

- name: Check OpenvSwitch system container package
  command: >
    atomic containers list --no-trunc -a -f container=openvswitch
  register: result
  when:
  - openshift.common.is_containerized | bool
  - openshift.common.is_openvswitch_system_container | bool

- name: Update OpenvSwitch system container package
  command: >
    atomic containers update openvswitch
  register: update_result
  changed_when: "'Extracting' in update_result.stdout"
  when:
  - openshift.common.is_containerized | bool
  - openshift.common.is_openvswitch_system_container | bool
  - openshift.common.version == openshift_version and "openvswitch" in result.stdout

- name: Uninstall OpenvSwitch system container package
  command: >
    atomic uninstall openvswitch
  failed_when: False
  when:
  - openshift.common.is_containerized | bool
  - openshift.common.is_openvswitch_system_container | bool
  - openshift.common.version != openshift_version and "openvswitch" in result.stdout

- name: Install OpenvSwitch system container package
  command: >
    atomic install --system --name=openvswitch {{ openshift.common.system_images_registry }}/{{ openshift.node.ovs_system_image }}:{{ openshift_image_tag }}
  when:
  - openshift.common.is_containerized | bool
  - openshift.common.is_openvswitch_system_container | bool
  - openshift.common.version != openshift_version or "openvswitch" not in result.stdout
  notify:
  - restart docker
